* Diagnosing COVID-19 using chest x-ray images

** What is the goal?

The main goal of this repository is to provide an "easy to use" tool that can be used to detect the patients' view position in chest x-ray images. So far, it is able to differentiate between =frontal=, =lateral= and non chest images.


* How to install the software:

The original implementation of this program has been programmed in [[www.python.org][Python]] using the [[www.pytorch.org][Pytorch]] deep learning toolkit and the [[www.fastai.ai][fast.ai]] library.  However, installing deep learning libraries in certain settings can be cumbersome or not convenient. We have simplified this process by encapsulating all the heavy lifting inside a [[www.docker.com][Docker]] container.

*** Install Docker:

Please follow the [[https://docs.docker.com/install/][guide]] to install [[www.docker.com][Docker]] for your operating system:

- [[https://docs.docker.com/docker-for-windows/install/][Windows]]
- [[https://docs.docker.com/docker-for-mac/install/][Mac]]
- [[https://docs.docker.com/install/linux/docker-ce/ubuntu/][GNU/Linux (Ubuntu)]]

If you are on Linux a want to use the GPU capabilities of your local machine, please be sure that you install the [[https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0)][nvidia-docker (version 2.0)]] packages. For this particular problem, we discourage it, as in most of our experiments, the software runs in less than 10 seconds without using the GPU.

*** Install Python:

A [[www.python.org][Python]] installation. Then, install all the required packages using =pip= as follows:

#+begin_src python
pip install pyfiglet docker
#+end_src

or using the requirements file:
#+begin_src python
pip install -r requirements.txt
#+end_src

* How to use it:

To use this tool, just run =python detect_chest_view.py --help= from the same source folder to see all the available options. The first time you run the software, it will download automatically the automated =docker container= from the [[https://hub.docker.com/][Docker Hub]].

** Mandatory parameters:
- input_image (=--input_image=): input scan to process. The input scan can be an image file (=jpeg=, =bmp=, etc...) or a  DICOM =dcm= file.

** Optional parameters:
- model (=--model=): Model to use. (not implemented yet).
- gpu use (=--gpu=): use GPU for faster inference (default=No).
- update (=--update=): update the Docker image.

** Example:

Just an example of how to use the software. Let's use some of the cases of the examples folder. In the case of =jpeg= file:

#+begin_src bash
python detect_chest_view.py --input_image examples/dcm/pneumonia_example.dcm
#+end_src

When finished, the software will generate a file called =pneumonia_example.csv= file with the predicted view:

* License:

This software is released under the version 3 of the GNU General Public License. Please read the license terms before using the software. A copy of this license is present in the root directory.

* Contact
Contact: [[https://github.com/sergivalverde][Sergi Valverde]], Postodoctoral researcher, University of Girona, Spain.
